# Generated by Powerlevel10k configuration wizard on 2024-01-01 at 00:00 UTC.
# Format: https://github.com/romkatv/powerlevel10k/blob/master/README.md#installation-and-configuration.
# Config for the "Classic" prompt style with "Unicode" character set.

typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    os_icon                 # os identifier
    dir                     # current directory
    vcs                     # git status
    prompt_char            # prompt symbol
)

typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    status                  # exit code of the last command
    command_execution_time  # duration of the last command
    background_jobs         # presence of background jobs
    direnv                 # direnv status (https://direnv.net/)
    virtualenv             # python virtual environment (https://docs.python.org/3/library/venv.html)
    node_version           # node.js version
    disk_usage             # disk usage
    ram                    # free RAM
    load                   # CPU load
    time                   # current time
)

# Основные настройки
typeset -g POWERLEVEL9K_MODE=nerdfont-complete
typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
typeset -g POWERLEVEL9K_PROMPT_ON_NEWLINE=true
typeset -g POWERLEVEL9K_RPROMPT_ON_NEWLINE=false
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''
typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='%F{blue}❯%f '

# Настройки цветов и стиля
typeset -g POWERLEVEL9K_COLOR_SCHEME='dark'
typeset -g POWERLEVEL9K_DIR_HOME_BACKGROUND=4
typeset -g POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND=4
typeset -g POWERLEVEL9K_DIR_ETC_BACKGROUND=4
typeset -g POWERLEVEL9K_DIR_DEFAULT_BACKGROUND=4

# Дополнительные настройки
typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
typeset -g POWERLEVEL9K_SHORTEN_STRATEGY="truncate_middle" 